### ISSUE TITLE
System.NullReferenceException When calling Stop()

### ISSUE THREAD

**Issue by Tilation** [jchristn/WatsonTcp#96] opened 2020-10-12 03:18 UTC
**Operating system and version:** Windows 10 x64
**Framework and runtime:** .NET Framework 4.7.2
**Issue encountered:** System.NullReferenceException when Stopping a server.
**Expected behavior:** The server should stop without errors.
**Steps to reproduce:** Instantiate a tcp server, and then call Stop()
**Sample code encapsulating the problem:**

```
WatsonTcpServer tcpServer = new WatsonTcpServer(ip, port);
[...]
tcpServer.Start();
[...]
tcpServer.Stop();   <---------
```

**Exception details:** System.NullReferenceException
![image](https://user-images.githubusercontent.com/48564654/95701232-66042800-0c1f-11eb-927d-454b3784d7e7.png)

**Comment by jchristn** [comment] 2020-10-12 03:30
Hi @Tilation could you help me reproduce this?  I just tried and I'm not getting an exception (using ```Test.Server``` and ```Test.Client``` projects)

![image](https://user-images.githubusercontent.com/1421081/95702216-8f618b80-0c00-11eb-9040-84fa5d39e02e.png)

**Comment by Tilation** [comment] 2020-10-12 15:16
Hi, I restarted the pc just in case, but the error is still showing up.
Note that I'm not connecting any clients, maybe that is what triggers the exception? Tries to close all connections first, but there are none?

This is the code, its a fresh WinForms project with a button.
```
    public partial class Form1 : Form
    {
        WatsonTcpServer sv;
        public Form1()
        {
            InitializeComponent();
        }

        private void Form1_Load(object sender, EventArgs e)
        {
            sv = new WatsonTcpServer("127.0.0.1",18493);
            sv.Start();
        }

        private void button1_Click(object sender, EventArgs e)
        {
            sv.Stop(); // <----- Error here
        }
    }
```

**Comment by jchristn** [comment] 2020-10-12 15:30
Ah, got it.  Testing in Winforms, give me a moment.  Thanks!

**Comment by jchristn** [comment] 2020-10-12 15:38
Interesting.  I used the ```Test.WinFormServer``` project and added try/catch blocks around ```.Start()``` and ```.Stop()```.  The exception seems to be happening outside of these methods (you can see there are no exception log statements showing up in the form itself, and the message ```Leaving bStop_Click``` shows properly).  

I do see in the debug output (bottom right) that there is an ```ObjectDisposedException``` thrown in ```System.dll``` and ```mscorlib.dll```.  I don't know what's causing those, but I would bet it's due to running the server inside the form (I'm not a winform expert unfortunately).
```
Exception thrown: 'System.ObjectDisposedException' in System.dll
Exception thrown: 'System.ObjectDisposedException' in mscorlib.dll
```

![image](https://user-images.githubusercontent.com/1421081/95764942-ff562d00-0c65-11eb-92a4-c5431af01e9f.png)

**Comment by jchristn** [comment] 2020-10-12 18:19
Hi @Tilation ok I figured out what is happening.  I changed the log message in this code block within the server's ```AcceptConnections()``` method to:
```
                catch (ObjectDisposedException)
                {
                    _Settings.Logger?.Invoke(_Header + "listener disposed");
                }
```
And the exception you see in the debug output (the one you caught) is being properly thrown when closing the listener using the ```Stop()``` method.  ```Stop()``` is requesting cancellation of the ```CancellationToken``` used by that method.

I'm not sure how to get it out of the debug output though.  If you want, you can remove ```ObjectDisposedException``` from Debug > Windows > Exception Settings > System.ObjectDisposedException and it shouldn't cause a break in your debug session after that.

If you know of another way I should be doing this I'd love to hear it.  

Cheers, Joel

**Comment by Tilation** [comment] 2020-10-15 18:07
I'll try testing it outside the form and I'll catch to you! Maybe de garbage collector is doing weird things

**Comment by jchristn** [comment] 2020-10-15 18:08
Thanks @Tilation let me know :)

**Comment by jchristn** [comment] 2020-10-20 16:23
Hi @Tilation wanted to see if you had any luck testing outside the form?  Cheers

**Comment by Tilation** [comment] 2020-10-20 23:48
It is working outside forms, I don't understand what's happening, but I ended using SimpleTCP in forms and that seems to work

**Comment by jchristn** [comment] 2020-10-21 00:01
Got it.  Thanks for the update @Tilation 

If you have any interested, I published an updated version today that caused a NullReferenceException in ```Stop()``` (I'm doing a total facepalm on it; I had misplaced a ```?``` on a logging statement).  

Closing this out.

**Closed by jchristn** 2020-10-21 00:01 UTC
