### ISSUE TITLE
Packet corruption

### ISSUE THREAD

**Issue by playingoDEERUX** [jchristn/WatsonTcp#88] opened 2020-08-09 22:30 UTC
I am sending a huge packet with SendAsync to my Server (and Send to my Client from the Server) why does it have missing/corrupted data sometimes? Like every 10th time I send this packet this occurs.
Is message framing integrated in Send/SendAsync?, I am also using Messages rather than Streams, is that perhaps the issue?

**Comment by jchristn** [comment] 2020-08-10 01:23
Hi @playingoDEERUX yes framing is included everywhere.  Could you provide sample code to reproduce this issue?  Thanks, Joel

**Comment by jchristn** [comment] 2020-08-10 01:34
Also what is the size of the data you send?  Are you sending a byte array or a stream from the sender side?  Are you consuming the data on the receiver side using MessageReceived or StreamReceived?

**Comment by playingoDEERUX** [comment] 2020-08-10 11:27
I am using MessageReceived and am running a public external server and am using Kernys.Bson.
I am sending a byte array from sender side.

private void Network_OnReceive(object sender, MessageReceivedFromServerEventArgs args)
        {
                BSONObject bsonResponse = SimpleBSON.Load(args.Data);
                string strVal = bsonResponse[NetHelper.NetTypes.Message].stringValue;
               
                switch (strVal)
                {
                        ...
This is how I receive the message.

**Comment by playingoDEERUX** [comment] 2020-08-10 11:31
On my client I send with WatsonTcpClient.SendAsync, on my server via WatsonTcpServer.Send

**Comment by playingoDEERUX** [comment] 2020-08-10 11:33
Also I realized this actually occurs on smaller size packets too (that are not necessarily 1MB)

**Comment by jchristn** [comment] 2020-08-10 13:58
Hi @playingoDEERUX thanks for the detail.  Would love to help find the source of the issue; this doesn't sound like an out of the ordinary use of WatsonTcp.

Are your client and server console applications?  If so could you turn on logging and capture the logs from when this occurs?  
```
client.DebugMessages = true;
client.Logger = Console.WriteLine;
// same for server
```

Are you using .NET Core or .NET Framework?  Which OS and version are you using?

Do you see the same issue with compression disabled?

Could you reproduce the issue using the code found in the ```Test.LargeMessages``` project?  Source code is here: https://github.com/jchristn/WatsonTcp/tree/master/Test.LargeMessages

Cheers, Joel

**Comment by playingoDEERUX** [comment] 2020-08-11 01:32
My client (that most likely has this issue) is running on winforms (will be able to log anyway under Visual Studio Debugger)
I am using .NET Core for the server and .NET Framework for the client
The range of what packets server sends are 100 bytes up to a few megabytes (4mb at max)
Here the error:

WatsonMessage] ReadHeaders found header demarcation
[WatsonMessage] BuildFromStream header processing complete
{"Status":"Normal","SyncRequest":false,"SyncResponse":false,"Compression":"Deflate","ContentLength":36,"Metadata":{}}
[WatsonMessage] ReadHeaders found header demarcation
[WatsonMessage] BuildStream exception: 
{
  "ClassName": "Newtonsoft.Json.JsonReaderException",
  "Message": "Unexpected character encountered while parsing value: R. Path '', line 0, position 0.",
  "Data": null,
  "InnerException": null,
  "HelpURL": null,
  "StackTraceString": "   at Newtonsoft.Json.JsonTextReader.ParseValue()\r\n   at Newtonsoft.Json.JsonTextReader.Read()\r\n   at Newtonsoft.Json.JsonReader.ReadForType(JsonContract contract, Boolean hasConverter)\r\n   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)\r\n   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)\r\n   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)\r\n   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)\r\n   at WatsonTcp.SerializationHelper.DeserializeJson[T](String json)\r\n   at WatsonTcp.WatsonMessage.<BuildFromStream>d__34.MoveNext()",
  "RemoteStackTraceString": null,
  "RemoteStackIndex": 0,
  "ExceptionMethod": "8\nParseValue\nNewtonsoft.Json, Version=12.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed\nNewtonsoft.Json.JsonTextReader\nBoolean ParseValue()",
  "HResult": -2146233088,
  "Source": "Newtonsoft.Json",
  "WatsonBuckets": null
}

[WatsonTcpClient] Message build failed due to disconnect
[WatsonTcpClient] Data receiver terminated
[WatsonTcpClient] Disposing
[WatsonTcpClient] Dispose complete
...
It also occurs without compression.
Could it perhaps be because I am sending two seperate packets from the server at the same time w/2 threads?

**Comment by jchristn** [comment] 2020-08-11 02:00
Thanks, this is helpful.  Generally when there is a deserialization exception, too much data has been read out of the stream.  What version are you running?  There's a bug that was fixed in 4.1.12.7 that fixed an overlapping write issue (which manifests itself as exactly this)

**Comment by playingoDEERUX** [comment] 2020-08-11 02:12
I am running the latest version, 4.1.12.7 on both server and client. Also I tried using Gzip compression and I think its broken because with that, from rarely disconnecting I always disconnect so I guess I'll be sticking to deflate for now.

**Comment by jchristn** [comment] 2020-08-11 02:22
Hmmm..  Since you're receiving message metadata, it indicates to me that you're (somehow) hitting a condition where it tries to read another message header immediately after reading a header, rather than reading the payload.  

I've been meaning to abandon ```SemaphoreSlim``` internally in favor of just simple locks; let me implement this now and post a new version for you to try.  Please give me an hour or so.  Cheers, Joel

**Comment by playingoDEERUX** [comment] 2020-08-11 02:24
Issues is fixed! It apparently was because my client received the Ping Packet together with another response packet at once, perhaps the new version will fix this so this wouldnt be relying on the shoulder of the users anymore but I found this confusing. Anyways hope the new version is going to get rid of this.
Thanks!

**Comment by jchristn** [comment] 2020-08-11 02:37
Understood :)  Would you be open to testing the attached .nupkg?  I didn't publish to Nuget yet until I give it some soak time on my end.  I changed the SemaphoreSlim constructor from (1) to (1, 1).  I think somehow under the hood it was increasing the max number of threads allowed to enter.


[WatsonTcp.4.1.12.8.nupkg.zip](https://github.com/jchristn/WatsonTcp/files/5054460/WatsonTcp.4.1.12.8.nupkg.zip)

**Comment by playingoDEERUX** [comment] 2020-08-11 15:21
I guess it fixed it, seems like the packets properly arrive.

**Comment by jchristn** [comment] 2020-08-11 21:02
Hi @playingoDEERUX please refer to v4.2.0, just committed (https://github.com/jchristn/WatsonTcp/commit/89dd514ce50cbca39051413ec7f0d8aec3b8405b) and published to NuGet (https://www.nuget.org/packages/WatsonTcp/4.2.0).  

There are a couple key changes:

1) You shouldn't be able to 'over-read' now when using streams, i.e. reading too many bytes and getting into the next message's header
2) Compression is gone, for now; it was causing too many problems across multiple OS and runtimes

Please re-open if any further issues.  

Cheers, Joel

**Closed by jchristn** 2020-08-11 21:02 UTC
