### ISSUE TITLE
Feature request: Data Compression

### ISSUE THREAD

**Issue by developervariety** [jchristn/WatsonTcp#68] opened 2020-04-14 00:16 UTC

**Comment by jchristn** [comment] 2020-04-15 05:11
Hi @developervariety thanks for filing this!  I have a version I'm about to publish that applies either Gzip or Deflate compression over the data payload.  It won't apply to the headers or user-supplied metadata because one of my design goals is to make sure that non-Watson systems can interact with Watson systems.  Applying compression over those would make that kind of integration quite challenging to do the compression over the headers and metadata too.  

I'm going to run some more tests in the next day or so to make sure everything works as intended and then I will publish and report back with the link to NuGet and to the commit.

Thanks again Justin!  Cheers

**Comment by jchristn** [comment] 2020-04-15 15:41
Hi @developervariety please check out v4.1.0 on NuGet, the latest commit, and the updated README.  Compression support is now provided for message data (not metadata/headers) using Gzip or Deflate.  Also added a shout-out to you for your support to the project in the README :) 

NuGet v4.1.0: https://www.nuget.org/packages/WatsonTcp/4.1.0
Commit: https://github.com/jchristn/WatsonTcp/commit/88a7a7a4a6127768f6d8982cb4bbd34a9b7409ca

Marking this as closed, please re-open if you find issues!  Cheers, Joel

**Closed by jchristn** 2020-04-15 15:41 UTC
Labels: enhancement

**Comment by jchristn** [comment] 2020-04-15 15:43
Here are the relevant README sections:
```
## Contributions

Special thanks to the following people for their support and contributions to this project!

- @brudo
- @MrMikeJJ
- @mikkleini
- @pha3z
- @crushedice
- @marek-petak
- @ozrecsec
- @developervariety
```

and

## Compression

Data compression was added in v4.1.0 to reduce bandwidth consumption for data send between client and server (thank you @developervariety for the suggestion).  Compression is applied only to the data and not to the headers or user-supplied metadata, because we wanted to keep framing simple to support external integration with Watson.  Please refer to *FRAMING.md* for details.

Compression is enabled as a property on either client or server, and this will instruct the instance to send message data using the specified compression method.  Compressed messages are automatically decompressed on the receiving side without any configuration required.  

The ```Compression``` property can be set to one of: ```Gzip```, ```Deflate```, ```None```.

```
using WatsonTcp;

using (WatsonTcpServer server = new WatsonTcpServer("127.0.0.1", 8000))
{
    using (WatsonTcpClient client = new WatsonTcpClient("127.0.0.1", 8000))
    {
        server.MessageReceived += ServerMessageReceived;
        server.Compression = CompressionType.Gzip;      // all message data sent from server now Gzip compressed
        server.Start();

        client.MessageReceived += ClientMessageReceived;
        client.Compression = CompressionType.None;      // client will not compress data it sends
        client.Start();
    }
}
```

**Comment by developervariety** [comment] 2020-04-15 16:40
Thank you so much @jchristn!

**Comment by developervariety** [comment] 2020-04-15 17:28
I've forked the repository so I could add custom compression support. As soon as I get time I'll work on it and send in a PR!

**Comment by jchristn** [comment] 2020-04-15 18:03
Perfect, thanks @developervariety !
