### ISSUE TITLE
New feature: implement SendRequest 

### ISSUE THREAD

**Issue by ozrecsec** [jchristn/WatsonTcp#58] opened 2020-03-20 13:29 UTC
hi jchristin,
I'm new to github, I've found your library very useful for my next project.
It's very easy to use and works very good.
I would like see in your WatsonTcpClient class an implementation of a method like this

`byte[] SendRequest(Dictionary<object,object>, string data)`

When the client sends this message it will wait for the response and then provide the response as return value.

When the server receives the Request it fires an event and after event management sends the response to the client.

Who manages the server event must set the response in a property of eventargs. Also the server have to respond very quickly :-)

I think that in this case the communication between the client and the server will be synchronous, i cannot send to server other requests until the current has no response.

I don't know if this is a good idea but this implementation makes the TCP calls more similar to method calls.

let me know what do you think about

Thanks

Ozrecsec

**Comment by jchristn** [comment] 2020-03-20 16:46
Hi @ozrecsec thanks so much for submitting this enhancement request.  I'll add it to the backlog!

**Comment by jchristn** [comment] 2020-03-21 16:41
Hi @ozrecsec let me know what you think :)

NuGet v3.1.0: https://www.nuget.org/packages/WatsonTcp/3.1.0
Commit: https://github.com/jchristn/WatsonTcp/commit/841d9fc11ae6a1a32d6888be9a1847f66a87d81a

Updated README.md has examples, as do the Test.Client and Test.Server projects.

**Comment by developervariety** [comment] 2020-03-22 14:36
I actually needed this too, thank you!

**Comment by jchristn** [comment] 2020-03-22 20:49
Thanks @developervariety and @ozrecsec please re-open if there are issues with this feature.

**Comment by developervariety** [comment] 2020-03-22 22:21
@jchristn any possible way to make another method which is a list of `Dictionary<object,object>` and without `string data`?

**Comment by jchristn** [comment] 2020-03-22 23:41
Hi @developervariety the ```Dictionary<object, object>``` is just to transfer metadata with the message.  I could amend the library to allow sending 0-byte messages with attached metadata, but changing the metadata from a ```Dictionary``` to ```List<Dictionary>``` isn't a priority, since your ```List<Dictionary>``` could simply be the value to a key in the metadata ```Dictionary```.

Do you have a use case that requires sending 0-byte messages?

Thanks!

**Comment by jchristn** [comment] 2020-03-23 00:39
Hi @developervariety this release exposes APIs to allow sending the metadata dictionary with no payload.  I also amended the APIs to provide better support for sending ```null```.

NuGet: https://www.nuget.org/packages/WatsonTcp/3.1.1
Commit: https://github.com/jchristn/WatsonTcp/commit/92b3119ceceebefdb771b1b73089e3baf9ec6cf3

Cheers!  Joel

PS - please reopen if you find any issues.

**Comment by developervariety** [comment] 2020-03-23 00:45
I was requesting it due to making my client depend on the server. I build a request (headers, parameters) on the server, and send it over to the client to be executed (http library).

Thank you for the swift responses and contributions!

**Comment by ozrecsec** [comment] 2020-03-23 09:22
Thank you so much!  :-) With this modify your library will be in my project.
I've only one question for you: there's a reason for the SyncRequestReceived that is an "action" instead of an Event like MessageReceived?

maybe i've to study a little bit more :-) but I don't see any valid reason to manage this in a different way from MessageReceived. 

I've expected some like  this :
`server.SyncRequestReceived += Server_SyncRequestReceived;`
.
.
.
`private void Server_SyncRequestReceived(object sender, SyncRequestReceivedEventArgs e){`
`        //the response is a property of eventargs in addition to the properties in standard MessageReceivedFromClientEventArgs`
`        e.SyncResponse = new SyncResponse("Hello back at you!");`
`}`


I've no problem to use your awesome library as is but to have a uniform way to use it's better have all in event manner

Excuse me for my bad english I hope it's quite clear

bye and thank you again
Ozrecsec from Italy

**Comment by ozrecsec** [comment] 2020-03-23 09:39
sorry but i've found a problem in my italian localization:

below the exception occurred.

DateTimeInvalidLocalFormat occurred
Message: Managed Debugging Assistant 'DateTimeInvalidLocalFormat' has detected a problem in 'C:\Users\ozrecsec\Desktop\TestWatsonTCP\TestWatsonTCP\bin\Debug\TestWatsonTCP.vshost.exe'.
Additional information: A UTC DateTime is being converted to text in a format that is only correct for local times. This can happen when calling DateTime.ToString using the 'z' format specifier, which will include a local time zone offset in the output. In that case, either use the 'Z' format specifier, which designates a UTC time, or use the 'o' format string, which is the recommended way to persist a DateTime in text. This can also occur when passing a DateTime to be serialized by XmlConvert or DataSet. If using XmlConvert.ToString, pass in XmlDateTimeSerializationMode.RoundtripKind to serialize correctly. If using DataSet, set the DateTimeMode on the DataColumn object to DataSetDateTime.Utc.

**Comment by jchristn** [comment] 2020-03-23 14:29
Agh, sorry about that.

Try this one.

NuGet v3.1.2: https://www.nuget.org/packages/WatsonTcp/3.1.2
Commit: https://github.com/jchristn/WatsonTcp/commit/d0fbc2ec3f4af4bc994ba0c1323f488de31c14ad

Please let me know if this works.

**Comment by ozrecsec** [comment] 2020-03-23 16:16
Thanks I'll try tomorrow :-) here it's 17:15 and i'll go to do other ;-)

**Comment by jchristn** [comment] 2020-03-23 16:23
No sweat, please re-open if there are problems!  Cheers

**Comment by developervariety** [comment] 2020-03-23 20:00
Hey, @jchristn! I'm having an issue with this sadly. Everytime I send a sync request from the client to the server, the logger returns saying the sync request has expired and has been discarded. Timeout is 10secs.

**Server**
```csharp
TcpServer = new WatsonTcpServer(null, 1337)
            {
                MaxConnections = 100,
                MutuallyAuthenticate = false,
                AcceptInvalidCertificates = false,
                PresharedKey = "be 0c 93 a4 3d b",
                SyncRequestReceived = OnSyncRequestReceived,
                Logger = log => { Logger.Debug(log); }
            };

            #region " Events "

            TcpServer.ClientConnected += OnClientConnected;
            TcpServer.ClientDisconnected += OnClientDisconnected;
            TcpServer.MessageReceived += (sender, args) => { };

            #endregion
```

**Client**
```csharp
TcpClient = new WatsonTcpClient("localhost", 1337)
            {
                ConnectTimeoutSeconds = 15,
                MutuallyAuthenticate = false,
                AcceptInvalidCertificates = false,
                SyncRequestReceived = OnSyncRequestReceived,
                Logger = log => { Logger.Debug(log); },
                AuthenticationRequested = OnAuthenticationRequested
            };

            #region " Events "

            TcpClient.ServerConnected += OnServerConnected;
            TcpClient.ServerDisconnected += OnServerDisconnected;
            TcpClient.MessageReceived += (sender, args) => { };
            TcpClient.AuthenticationSucceeded += OnAuthenticationSucceeded;
            TcpClient.AuthenticationFailure += OnAuthenticationFailure;

            #endregion
```

Am I possibly doing something wrong here?

**Comment by jchristn** [comment] 2020-03-23 20:40
Hi @developervariety I see you have the preshared key set on the server.  Are you setting it on the client?  Are you implementing ```AuthenticationRequested```?  

You could also try implementing parts of your code in the ```Test.Server``` and ```Test.Client``` packages to reproduce.  That would be a simple way of sharing specific code with reproducible failures.  

Cheers, Joel

**Comment by developervariety** [comment] 2020-03-23 20:47
Yes, I have `AuthenticationRequested` implemented on the client, and that is working fine. I will be downloading the project, and build it to see if I can reproduce it.

**Comment by developervariety** [comment] 2020-03-23 21:10
@jchristn I just did a test with no `Data` just `Metadata` and the same problem occurred.

Server console:
```
Server IP: [127.0.0.1]
Server port: [9000]
Use SSL: [y/N]?
[WatsonTcpServer] Starting on 127.0.0.1:9000
Command [? for help]: [WatsonTcpServer] Accepted connection from 127.0.0.1:50738
[WatsonTcpServer] Starting data receiver for 127.0.0.1:50738
Client connected: 127.0.0.1:50738
[WatsonTcpServer] Expired synchronous request received and discarded from 127.0.0.1:50738
```

Client method:
```csharp
private static void SendAndWait()
        {
            string userInput = InputString("Data:", null, false);
            int timeoutMs = InputInteger("Timeout (milliseconds):", 5000, true, false);

            try
            {Dictionary<object, object> metadata = new Dictionary<object, object>
                {
                    ["directory"] = "redacted",
                    ["method"] = "redacted",
                    ["public_key"] = "redacted"
                };
                
                SyncResponse resp = client.SendAndWait(metadata, timeoutMs);
                if (resp.Metadata != null && resp.Metadata.Count > 0)
                {
                    Console.WriteLine("Metadata:");
                    foreach (KeyValuePair<object, object> curr in resp.Metadata)
                    {
                        Console.WriteLine("  " + curr.Key.ToString() + ": " + curr.Value.ToString());
                    }
                }

                Console.WriteLine("Response: " + Encoding.UTF8.GetString(resp.Data));
            }
            catch (Exception e)
            {
                Console.WriteLine("Exception: " + e.ToString());
            }
        }
```

**Comment by jchristn** [comment] 2020-03-23 21:51
Hi @developervariety just reproduced this, looking into it now!

**Comment by jchristn** [comment] 2020-03-23 22:23
Ok I think I have a solution here.  The issue was around conversion to UTC.  I don't know, however, if this fix will break the fix I put in for @ozrecsec so I'll need confirmation.  Also both Test.Client and Test.Server now have a command called ```sendandwait empty``` for this purpose.

![image](https://user-images.githubusercontent.com/1421081/77368356-49eb7880-6d19-11ea-8099-eea1dd82ef20.png)

NuGet v3.1.3: https://www.nuget.org/packages/WatsonTcp/3.1.3
Commit: https://github.com/jchristn/WatsonTcp/commit/495cffc36e069b7c0234f8ea3fc659b2a6273724

Please let me know if any issues either way.

**Comment by ozrecsec** [comment] 2020-03-24 09:36
ok, i've tested directly the 3.1.3 version and works perfectly. thanks so much

I've noticed that my problem was because i've put client and server (only for test purpose) in the same application.... if I launch two exe separatly it works fine.

bye

**Comment by jchristn** [comment] 2020-03-24 14:50
Thanks for confirming @ozrecsec - just as an FYI, you should be able to have both in the same program.  I do that all the time with no issue.  For example, see: https://github.com/jchristn/WatsonTcp/blob/master/Test.Throughput/Test1.cs

Cheers, Joel

**Comment by ozrecsec** [comment] 2020-03-24 15:48
ok, but with SendAndWait it will wait until the timeoutException fires.
My tests in single application worked well until i tested the SendAndWait funcionality.
But this is not a real problem, it's a nonsense to have client and server in the same application :-)

Ciao
Michele (alias ozrecsec)

**Comment by developervariety** [comment] 2020-03-24 16:40
@jchristn it appears this bug is back again, but only when the server requests data from the client with `SendAndWait`.

**Comment by jchristn** [comment] 2020-03-24 17:53
Hi @developervariety reopening this and looking into it now!

**Comment by jchristn** [comment] 2020-03-24 17:55
Server on left, client on right, ```sendandwait``` with data from server to client:
![image](https://user-images.githubusercontent.com/1421081/77460021-cb94e200-6dbd-11ea-99f5-a2f559b1114a.png)

```sendandwait empty``` from server to client:
![image](https://user-images.githubusercontent.com/1421081/77460124-e9fadd80-6dbd-11ea-86ce-1e149f746953.png)

Hi @developervariety this seems to be working on my end.  Are you listening on ```127.0.0.1``` or doing this between different hosts/different IP addresses?  Cheers, Joel

**Comment by developervariety** [comment] 2020-03-24 18:21
I am sending a sync request as soon as the client connects to the server. I have checked to see if the client was indeed sending back a `SyncResponse`, and it does. It's populated correctly and it isn't `null`.

__Server__
```csharp
private static void OnClientConnected(object sender, ClientConnectedEventArgs e)
        {
            Logger.Information("A client has connected. Host=[{host}]", e.IpPort);

            SyncResponse syncResponse;
            Dictionary<object, object> metadata = new Dictionary<object, object>
            {
                ["namespace"] = "License",
                ["method"] = "SendVerification"
            };
            
            try
            {
                syncResponse = TcpServer.SendAndWait(e.IpPort, metadata, 100000);
                Console.WriteLine(syncResponse.Metadata["license"]);
            }
            catch (TimeoutException)
            {
                TcpServer.DisconnectClient(e.IpPort);
                Logger.Warning("A client did not send verification within time frame. Host=[{host}]", e.IpPort);
            }
        }
```

__Client__
```csharp
private static SyncResponse OnSyncRequestReceived(SyncRequest e)
        {
            Logger.Debug("Remote server has sent a sync request. Expiration=[{expiration}]", e.ExpirationUtc);

            if (e.Metadata.ContainsKey("class"))
            {
                Type t1 = Type.GetType($"Client.Core.Network.{e.Metadata["namespace"]}");
                Type t2 = t1.GetNestedType($"{e.Metadata["class"]}");
                object obj = Activator.CreateInstance(t2);

                MethodInfo methodInfo = t2.GetMethod($"{e.Metadata["method"]}");
                return methodInfo?.Invoke(obj, new object[] {e}) as SyncResponse;
            }
            else
            {
                Type t1 = Type.GetType($"Client.Core.Network.{e.Metadata["namespace"]}");
                object obj = Activator.CreateInstance(t1);

                MethodInfo methodInfo = t1.GetMethod($"{e.Metadata["method"]}");
                return methodInfo?.Invoke(obj, new object[] {e}) as SyncResponse;
            }
        }
```

**Comment by jchristn** [comment] 2020-03-24 18:38
Ok so to confirm, the client is connecting successfully, which indicates that there is no network/firewall issue.

How/where are you confirming that SyncResponse was populated and sent?

**Comment by developervariety** [comment] 2020-03-24 18:43
Yes, communication between server and client is perfect. I confirmed `SyncResponse` is populated (not sure if it's sent) and not null by introducing a variable and debugging before returning `SyncResponse`.

**Comment by developervariety** [comment] 2020-03-24 19:00
Alright so I just added a 10sec wait before sending the client a sync request, and it is working!

**Comment by jchristn** [comment] 2020-03-24 19:09
That's so weird.  Is the client connecting before you have fully instantiated the server?

**Comment by developervariety** [comment] 2020-03-24 23:08
Yes, the server is fully initiated. Not sure why that happens, but it's working and that's what matters. You can close this issue, thank you so much!

**Closed** 2020-03-24 23:12 UTC
Labels: enhancement
