### ISSUE TITLE
Send message and disconnect without delay causes merge of message on server

### ISSUE THREAD

**Issue by ozrecsec** [jchristn/WatsonTcp#70] opened 2020-04-17 12:43 UTC
Hi, I'm in trouble with a particular case.

If my client sends a message to the server and immediatly closes the connection the server receives the message containing sended data and also the header of the "closing" message.

here below my output:

    Server listening on port 23456. press enter to close
    Client connected: 10.10.3.12:34746
    Message received from 10.10.3.12:34746: ciao{"Status":"Disconnecting","SyncRequest":false,"SyncResponse":false,"Compression":"None","ContentLength":0,"Metadata":{}}
    
    
    Client DISCONNECTED: 10.10.3.12:34746
    
    
If I put a delay of 200ms between send and dispose my message is correct and contains only my data:

    Client connected: 10.10.3.12:34751
    Message received from 10.10.3.12:34751: ciao
    Client DISCONNECTED: 10.10.3.12:34751

Here the server code:

    class Program
    {
        static string clientIpPort;
        static WatsonTcpServer srv;

        static void Main(string[] args)
        {
            srv = new WatsonTcpServer("", 23456);
            srv.ClientConnected += Srv_ClientConnected;
            srv.ClientDisconnected += Srv_ClientDisconnected;
            srv.MessageReceived += Srv_MessageReceived;
            srv.SyncRequestReceived = SyncRequestReceived;

            srv.Start();
            Console.WriteLine("Server listening on port 23456. press enter to close");
            Console.ReadLine();

        }

        private static void Srv_MessageReceived(object sender, MessageReceivedFromClientEventArgs e)
        {
            Console.WriteLine($"Message received from {e.IpPort}: {Encoding.UTF8.GetString(e.Data)}");
        }

        private static void Srv_ClientDisconnected(object sender, ClientDisconnectedEventArgs e)
        {
            clientIpPort = null;
            Console.WriteLine($"Client DISCONNECTED: {e.IpPort}");
        }

        private static SyncResponse SyncRequestReceived(SyncRequest req)
        {
            Console.WriteLine($"Syncrequest received from {req.IpPort}: {Encoding.UTF8.GetString(req.Data)}");
            SyncResponse ret;

            System.Threading.Thread.Sleep(5000);
            ret = new SyncResponse(req, "Long work done :-)");

            Console.WriteLine("Syncrequest completed");
            return ret;
        }

        private static void Srv_ClientConnected(object sender, ClientConnectedEventArgs e)
        {
            clientIpPort = e.IpPort;
            Console.WriteLine($"Client connected: {e.IpPort}");
        }
    }

And here the client code:

    class Program
    {
        static void Main(string[] args)
        {
    
            Console.WriteLine("press enter to connect, send message and disconnect");
            Console.ReadLine();
    
            WatsonTcpClient cli = new WatsonTcpClient("localhost", 23456);
            cli.ServerConnected += Cli_ServerConnected;
            cli.MessageReceived += Cli_MessageReceived;
            cli.DebugMessages = true;
            cli.Logger = log;
            cli.Start();
    
            cli.Send("ciao");
            //System.Threading.Thread.Sleep(200); without this the server receives a wrong message
            cli.Dispose();
            cli = null;
    
            Console.WriteLine("press enter to close");
            Console.ReadLine();
        }
    
        private static void log(string txt)
        {
            Console.WriteLine(DateTime.Now.ToString("HH:mm:ss.fff") + " --> " + txt);
        }
    
        private static void Cli_MessageReceived(object sender, MessageReceivedFromServerEventArgs e)
        {
            Console.WriteLine($"Message received from server: {Encoding.UTF8.GetString(e.Data)}");
        }
    
        private static void Cli_ServerConnected(object sender, EventArgs e)
        {
            Console.WriteLine($"Connected to server");
        }
    }

Maybe the disconnect don't wait the completion of last send?
Thanks so much
Michele (ozrecsec)

**Comment by jchristn** [comment] 2020-04-17 14:21
Hi Michele, message received and I will see if I can reproduce and fix this today!

**Comment by jchristn** [comment] 2020-04-17 16:35
Reproduced.
![image](https://user-images.githubusercontent.com/1421081/79592332-b5add080-808e-11ea-83b0-d32518ecd750.png)

Seems like a .Flush issue somewhere.  Working on this now.

**Comment by jchristn** [comment] 2020-04-17 16:40
Found in ```WatsonMessage.cs```
![image](https://user-images.githubusercontent.com/1421081/79592787-62884d80-808f-11ea-8182-a8afa7abfcbf.png)

I recall having to make this change because of something with SSL and compression.  Testing the fix.

**Comment by jchristn** [comment] 2020-04-17 16:43
Ok, yes, there is an issue with SSL and compression that caused me to read the stream fully.  It appears the compression stream for some reason is not advancing when read.  It will take me a while to dive into this.  If you're not using SSL, you can switch the line of code as above and be fine.  Sorry you encountered this!  I'll get it resolved ASAP.

**Comment by jchristn** [comment] 2020-04-17 17:16
Testing a version to commit and publish to NuGet.

**Comment by jchristn** [comment] 2020-04-17 17:59
Update: I can't get around the compression bug when SSL is used.  However this is more a corner case, and the fix for the broader use cases is more important.  Going to publish this version, and release note the issue.

**Comment by jchristn** [comment] 2020-04-17 18:07
Hi @ozrecsec I just pushed v4.1.1 to NuGet and everything works great *except* compression with SSL (@developervariety please be aware of this since it was an enhancement you requested)

Please confirm the fix and close the issue.

NuGet: https://www.nuget.org/packages/WatsonTcp/4.1.1
Commit: https://github.com/jchristn/WatsonTcp/commit/aa24fce5b5a4b71caf3a7cdeb2863190ee747947

Thanks for letting me know about this issue!  Cheers, Joel

**Closed** 2020-04-19 03:52 UTC
