### ISSUE TITLE
Disconnect not recognized -> High CPU Usage

### ISSUE THREAD

**Issue by Jyck** [jchristn/WatsonTcp#110] opened 2020-12-18 13:48 UTC
Server on Net 4.7.2
Client on Net 4.x 

running as apk on android, all is fine.
Close client app -> server recorgnize disconnect.
EnableTcpKeepAlives on server does not make a difference

running under BlueStacks Emulator, app starts,  connection is ok.
In idle mode (connection is ok but atm no data is transfered)  Close App -> Server didnt recorgnize disconnect. 
Server CPU Load increase from nearly zero to 20% and stay there.
Its possible to start the app again, all is working fine, connection is ok, close the app the same as above
now we have two "connected" clients and 40%CPU

if i do nothing the server stay with the high cpu load.
if i call now SendAsync with some data the disconnects gets recognized and the server cpu load is normal:
[WatsonMessage] non-graceful termination by peer
[WatsonTcpServer] disconnect detected for client xxxx
[WatsonTcpServer] client xxxx disconnected

its possible to write some ping functions, but this should not be the solution.

**Comment by jchristn** [comment] 2020-12-18 16:25
Hi @Jyck could you use something like ANTS Performance Profiler to see what the library is doing when you close the app in BlueStacks? I unfortunately don't have this environment.

**Comment by Jyck** [comment] 2020-12-18 18:24
ok here we go.

in short:
```
<?xml version="1.0" encoding="utf-8"?>
<PerformanceData>
    <ANTS version="10.6.1.2299" />
    <CreationTime>12/18/2020 19:21:04</CreationTime>
    <Range start-ms="23034" finish-ms="42723" />
    <TickRate>0Hz</TickRate>
    <Options remove-overhead="yes" />
    <Targets>
        <Process>
            <Name>PRServer.exe</Name>
            <PID>21020</PID>
            <Architecture>x64</Architecture>
            <ProfilingMode>Sampling</ProfilingMode>
            <Threads>
                <Thread>
                    <TID>21024</TID>
                    <Name>[5220] Untitled thread</Name>
                </Thread>
                <Thread>
                    <TID>21156</TID>
                    <Name>[52a4] Untitled thread</Name>
                </Thread>
                <Thread>
                    <TID>20960</TID>
                    <Name>[51e0] Untitled thread</Name>
                </Thread>
                <Thread>
                    <TID>20192</TID>
                    <Name>[4ee0] Untitled thread</Name>
                </Thread>
                <Thread>
                    <TID>21336</TID>
                    <Name>[5358] Untitled thread</Name>
                </Thread>
                <Thread>
                    <TID>19776</TID>
                    <Name>[4d40] Untitled thread</Name>
                </Thread>
                <Thread>
                    <TID>12652</TID>
                    <Name>[316c] Untitled thread</Name>
                </Thread>
                <Thread>
                    <TID>21080</TID>
                    <Name>[5258] Untitled thread</Name>
                </Thread>
            </Threads>
        </Process>
    </Targets>
    <CallTree>
        <Method class="System.Threading._IOCompletionCallback" name="PerformIOCompletionCallback" parameters="uint errorCode, uint numBytes, NativeOverlapped* pOVERLAP" PID="21020">
            <HitCount>1</HitCount>
            <CPU ticks="982892722" millisecs="98289.2722" percent="70.8378" />
            <Wallclock ticks="982892722" millisecs="98289.2722" percent="70.8378" />
            <WithSelf ticks="8795988" millisecs="879.5988" percent-cpu="0.6339" percent-wallclock="0.6339" />
            <Method name="22 hidden methods without source" special="Filtered" PID="21020">
                <HitCount>22</HitCount>
                <CPU ticks="974096734" millisecs="97409.6734" percent="70.2039" />
                <Wallclock ticks="974096734" millisecs="97409.6734" percent="70.2039" />
                <WithSelf ticks="41368260" millisecs="4136.8260" percent-cpu="2.9814" percent-wallclock="2.9814" />
                <Method class="WatsonTcp.WatsonMessage+&lt;BuildFromStream&gt;d__33" name="MoveNext" PID="21020" has-source="yes">
                    <HitCount>1</HitCount>
                    <CPU ticks="932728474" millisecs="93272.8474" percent="67.2225" />
                    <Wallclock ticks="932728474" millisecs="93272.8474" percent="67.2225" />
                    <WithSelf ticks="193464567" millisecs="19346.4567" percent-cpu="13.9431" percent-wallclock="13.9431" />
                    <Method name="18 hidden methods without source" special="Filtered" PID="21020">
                        <HitCount>18</HitCount>
                        <CPU ticks="734385953" millisecs="73438.5953" percent="52.9278" />
                        <Wallclock ticks="734385953" millisecs="73438.5953" percent="52.9278" />
                        <WithSelf ticks="734385953" millisecs="73438.5953" percent-cpu="52.9278" percent-wallclock="52.9278" />
                    </Method>
                </Method>
            </Method>
        </Method>
        <Method class="System.Threading.ThreadHelper" name="ThreadStart" PID="21020">
            <HitCount>1</HitCount>
            <CPU ticks="196884978" millisecs="19688.4978" percent="14.1897" />
            <Wallclock ticks="196884978" millisecs="19688.4978" percent="14.1897" />
            <WithSelf ticks="0" millisecs="0.0000" percent-cpu="0.0000" percent-wallclock="0.0000" />
            <Method name="3 hidden methods without source" special="Filtered" PID="21020">
                <HitCount>3</HitCount>
                <CPU ticks="196884978" millisecs="19688.4978" percent="14.1897" />
                <Wallclock ticks="196884978" millisecs="19688.4978" percent="14.1897" />
                <WithSelf ticks="0" millisecs="0.0000" percent-cpu="0.0000" percent-wallclock="0.0000" />
                <Method class="PRServer.Logger" name="Flush" PID="21020" has-source="yes">
                    <HitCount>1</HitCount>
                    <CPU ticks="196884978" millisecs="19688.4978" percent="14.1897" />
                    <Wallclock ticks="196884978" millisecs="19688.4978" percent="14.1897" />
                    <WithSelf ticks="0" millisecs="0.0000" percent-cpu="0.0000" percent-wallclock="0.0000" />
                    <Method name="1 hidden methods without source" special="Filtered" PID="21020">
                        <HitCount>1</HitCount>
                        <CPU ticks="196884978" millisecs="19688.4978" percent="14.1897" />
                        <Wallclock ticks="196884978" millisecs="19688.4978" percent="14.1897" />
                        <WithSelf ticks="196884978" millisecs="19688.4978" percent-cpu="14.1897" percent-wallclock="14.1897" />
                    </Method>
                </Method>
            </Method>
        </Method>
        <Method class="PRServer.Program" name="Main" PID="21020" has-source="yes">
            <HitCount>1</HitCount>
            <CPU ticks="196884620" millisecs="19688.4620" percent="14.1896" />
            <Wallclock ticks="196884620" millisecs="19688.4620" percent="14.1896" />
            <WithSelf ticks="0" millisecs="0.0000" percent-cpu="0.0000" percent-wallclock="0.0000" />
            <Method name="28 hidden methods without source" special="Filtered" PID="21020">
                <HitCount>28</HitCount>
                <CPU ticks="196884620" millisecs="19688.4620" percent="14.1896" />
                <Wallclock ticks="196884620" millisecs="19688.4620" percent="14.1896" />
                <WithSelf ticks="196884620" millisecs="19688.4620" percent-cpu="14.1896" percent-wallclock="14.1896" />
            </Method>
        </Method>
    </CallTree>
</PerformanceData>
```

Detailed:
```
<?xml version="1.0" encoding="utf-8"?>
<PerformanceData>
    <ANTS version="10.6.1.2299" />
    <CreationTime>12/18/2020 19:19:33</CreationTime>
    <Range start-ms="23034" finish-ms="42723" />
    <TickRate>0Hz</TickRate>
    <Options remove-overhead="yes" />
    <Targets>
        <Process>
            <Name>PRServer.exe</Name>
            <PID>21020</PID>
            <Architecture>x64</Architecture>
            <ProfilingMode>Sampling</ProfilingMode>
            <Threads>
                <Thread>
                    <TID>21024</TID>
                    <Name>[5220] Untitled thread</Name>
                </Thread>
                <Thread>
                    <TID>21156</TID>
                    <Name>[52a4] Untitled thread</Name>
                </Thread>
                <Thread>
                    <TID>20960</TID>
                    <Name>[51e0] Untitled thread</Name>
                </Thread>
                <Thread>
                    <TID>20192</TID>
                    <Name>[4ee0] Untitled thread</Name>
                </Thread>
                <Thread>
                    <TID>21336</TID>
                    <Name>[5358] Untitled thread</Name>
                </Thread>
                <Thread>
                    <TID>19776</TID>
                    <Name>[4d40] Untitled thread</Name>
                </Thread>
                <Thread>
                    <TID>12652</TID>
                    <Name>[316c] Untitled thread</Name>
                </Thread>
                <Thread>
                    <TID>21080</TID>
                    <Name>[5258] Untitled thread</Name>
                </Thread>
            </Threads>
        </Process>
    </Targets>
    <CallTree>
        <Method class="System.Threading._IOCompletionCallback" name="PerformIOCompletionCallback" parameters="uint errorCode, uint numBytes, NativeOverlapped* pOVERLAP" PID="21020">
            <HitCount>1</HitCount>
            <CPU ticks="982892722" millisecs="98289.2722" percent="70.8378" />
            <Wallclock ticks="982892722" millisecs="98289.2722" percent="70.8378" />
            <WithSelf ticks="8795988" millisecs="879.5988" percent-cpu="0.6339" percent-wallclock="0.6339" />
            <Method class="System.Net.Sockets.BaseOverlappedAsyncResult" name="CompletionPortCallback" parameters="uint errorCode, uint numBytes, NativeOverlapped* nativeOverlapped" PID="21020">
                <HitCount>1</HitCount>
                <CPU ticks="974096734" millisecs="97409.6734" percent="70.2039" />
                <Wallclock ticks="974096734" millisecs="97409.6734" percent="70.2039" />
                <WithSelf ticks="623069" millisecs="62.3069" percent-cpu="0.0449" percent-wallclock="0.0449" />
                <Method class="System.Net.LazyAsyncResult" name="ProtectedInvokeCallback" parameters="object result, IntPtr userToken" PID="21020">
                    <HitCount>1</HitCount>
                    <CPU ticks="973473665" millisecs="97347.3665" percent="70.1590" />
                    <Wallclock ticks="973473665" millisecs="97347.3665" percent="70.1590" />
                    <WithSelf ticks="273180" millisecs="27.3180" percent-cpu="0.0197" percent-wallclock="0.0197" />
                    <Method class="System.Net.ContextAwareResult" name="Complete" parameters="IntPtr userToken" PID="21020">
                        <HitCount>1</HitCount>
                        <CPU ticks="973200485" millisecs="97320.0485" percent="70.1393" />
                        <Wallclock ticks="973200485" millisecs="97320.0485" percent="70.1393" />
                        <WithSelf ticks="263075" millisecs="26.3075" percent-cpu="0.0190" percent-wallclock="0.0190" />
                        <Method class="System.Threading.ExecutionContext" name="Run" parameters="ExecutionContext executionContext, ContextCallback callback, object state" PID="21020">
                            <HitCount>1</HitCount>
                            <CPU ticks="972937410" millisecs="97293.7410" percent="70.1204" />
                            <Wallclock ticks="972937410" millisecs="97293.7410" percent="70.1204" />
                            <WithSelf ticks="137084" millisecs="13.7084" percent-cpu="0.0099" percent-wallclock="0.0099" />
                            <Method class="System.Threading.ExecutionContext" name="Run" parameters="ExecutionContext executionContext, ContextCallback callback, object state, bool preserveSyncCtx" PID="21020">
                                <HitCount>1</HitCount>
                                <CPU ticks="972800326" millisecs="97280.0326" percent="70.1105" />
                                <Wallclock ticks="972800326" millisecs="97280.0326" percent="70.1105" />
                                <WithSelf ticks="2107949" millisecs="210.7949" percent-cpu="0.1519" percent-wallclock="0.1519" />
                                <Method class="System.Threading.ExecutionContext" name="RunInternal" parameters="ExecutionContext executionContext, ContextCallback callback, object state, bool preserveSyncCtx" PID="21020">
                                    <HitCount>1</HitCount>
                                    <CPU ticks="970692377" millisecs="97069.2377" percent="69.9586" />
                                    <Wallclock ticks="970692377" millisecs="97069.2377" percent="69.9586" />
                                    <WithSelf ticks="4956006" millisecs="495.6006" percent-cpu="0.3572" percent-wallclock="0.3572" />
                                    <Method class="System.Net.LazyAsyncResult" name="Complete" parameters="IntPtr userToken" PID="21020">
                                        <HitCount>1</HitCount>
                                        <CPU ticks="965736371" millisecs="96573.6371" percent="69.6014" />
                                        <Wallclock ticks="965736371" millisecs="96573.6371" percent="69.6014" />
                                        <WithSelf ticks="5353879" millisecs="535.3879" percent-cpu="0.3859" percent-wallclock="0.3859" />
                                        <Method class="System.Net.FixedSizeReader" name="ReadCallback" parameters="IAsyncResult transportResult" PID="21020">
                                            <HitCount>1</HitCount>
                                            <CPU ticks="960382492" millisecs="96038.2492" percent="69.2155" />
                                            <Wallclock ticks="960382492" millisecs="96038.2492" percent="69.2155" />
                                            <WithSelf ticks="3307995" millisecs="330.7995" percent-cpu="0.2384" percent-wallclock="0.2384" />
                                            <Method class="System.Net.FixedSizeReader" name="CheckCompletionBeforeNextRead" parameters="int bytes" PID="21020">
                                                <HitCount>1</HitCount>
                                                <CPU ticks="957074497" millisecs="95707.4497" percent="68.9771" />
                                                <Wallclock ticks="957074497" millisecs="95707.4497" percent="68.9771" />
                                                <WithSelf ticks="566115" millisecs="56.6115" percent-cpu="0.0408" percent-wallclock="0.0408" />
                                                <Method class="System.Net.AsyncProtocolRequest" name="CompleteRequest" parameters="int result" PID="21020">
                                                    <HitCount>1</HitCount>
                                                    <CPU ticks="956508382" millisecs="95650.8382" percent="68.9363" />
                                                    <Wallclock ticks="956508382" millisecs="95650.8382" percent="68.9363" />
                                                    <WithSelf ticks="234846" millisecs="23.4846" percent-cpu="0.0169" percent-wallclock="0.0169" />
                                                    <Method class="System.Net.Security._SslStream" name="ReadHeaderCallback" parameters="AsyncProtocolRequest asyncRequest" PID="21020">
                                                        <HitCount>1</HitCount>
                                                        <CPU ticks="956273536" millisecs="95627.3536" percent="68.9194" />
                                                        <Wallclock ticks="956273536" millisecs="95627.3536" percent="68.9194" />
                                                        <WithSelf ticks="117644" millisecs="11.7644" percent-cpu="0.0085" percent-wallclock="0.0085" />
                                                        <Method class="System.Net.Security._SslStream" name="StartFrameBody" parameters="int readBytes, byte[] buffer, int offset, int count, AsyncProtocolRequest asyncRequest" PID="21020">
                                                            <HitCount>1</HitCount>
                                                            <CPU ticks="956155892" millisecs="95615.5892" percent="68.9109" />
                                                            <Wallclock ticks="956155892" millisecs="95615.5892" percent="68.9109" />
                                                            <WithSelf ticks="195535" millisecs="19.5535" percent-cpu="0.0141" percent-wallclock="0.0141" />
                                                            <Method class="System.Net.LazyAsyncResult" name="ProtectedInvokeCallback" parameters="object result, IntPtr userToken" PID="21020">
                                                                <HitCount>1</HitCount>
                                                                <CPU ticks="955960357" millisecs="95596.0357" percent="68.8968" />
                                                                <Wallclock ticks="955960357" millisecs="95596.0357" percent="68.8968" />
                                                                <WithSelf ticks="1678675" millisecs="167.8675" percent-cpu="0.1210" percent-wallclock="0.1210" />
                                                                <Method class="System.Net.LazyAsyncResult" name="Complete" parameters="IntPtr userToken" PID="21020">
                                                                    <HitCount>1</HitCount>
                                                                    <CPU ticks="954281682" millisecs="95428.1682" percent="68.7758" />
                                                                    <Wallclock ticks="954281682" millisecs="95428.1682" percent="68.7758" />
                                                                    <WithSelf ticks="2079660" millisecs="207.9660" percent-cpu="0.1499" percent-wallclock="0.1499" />
                                                                    <Method class="System.Threading.Tasks.TaskFactory&lt;TResult&gt;+FromAsyncTrimPromise&lt;TResult, TInstance&gt;" name="CompleteFromAsyncResult" parameters="IAsyncResult asyncResult" PID="21020">
                                                                        <HitCount>1</HitCount>
                                                                        <CPU ticks="952202022" millisecs="95220.2022" percent="68.6259" />
                                                                        <Wallclock ticks="952202022" millisecs="95220.2022" percent="68.6259" />
                                                                        <WithSelf ticks="116852" millisecs="11.6852" percent-cpu="0.0084" percent-wallclock="0.0084" />
                                                                        <Method class="System.Threading.Tasks.TaskFactory&lt;TResult&gt;+FromAsyncTrimPromise&lt;TResult, TInstance&gt;" name="Complete" parameters="TInstance thisRef, Func&lt;TInstance, IAsyncResult, TResult&gt; endMethod, IAsyncResult asyncResult, bool requiresSynchronization" PID="21020">
                                                                            <HitCount>1</HitCount>
                                                                            <CPU ticks="952085170" millisecs="95208.5170" percent="68.6175" />
                                                                            <Wallclock ticks="952085170" millisecs="95208.5170" percent="68.6175" />
                                                                            <WithSelf ticks="3778243" millisecs="377.8243" percent-cpu="0.2723" percent-wallclock="0.2723" />
                                                                            <Method class="System.Threading.Tasks.Task&lt;int&gt;" name="TrySetResult" parameters="TResult result" PID="21020">
                                                                                <HitCount>1</HitCount>
                                                                                <CPU ticks="948306927" millisecs="94830.6927" percent="68.3452" />
                                                                                <Wallclock ticks="948306927" millisecs="94830.6927" percent="68.3452" />
                                                                                <WithSelf ticks="996056" millisecs="99.6056" percent-cpu="0.0718" percent-wallclock="0.0718" />
                                                                                <Method class="System.Threading.Tasks.Task" name="FinishContinuations" PID="21020">
                                                                                    <HitCount>1</HitCount>
                                                                                    <CPU ticks="947310871" millisecs="94731.0871" percent="68.2734" />
                                                                                    <Wallclock ticks="947310871" millisecs="94731.0871" percent="68.2734" />
                                                                                    <WithSelf ticks="4069625" millisecs="406.9625" percent-cpu="0.2933" percent-wallclock="0.2933" />
                                                                                    <Method class="System.Threading.Tasks.AwaitTaskContinuation" name="RunOrScheduleAction" parameters="Action action, bool allowInlining, Task currentTask" PID="21020">
                                                                                        <HitCount>1</HitCount>
                                                                                        <CPU ticks="943241246" millisecs="94324.1246" percent="67.9801" />
                                                                                        <Wallclock ticks="943241246" millisecs="94324.1246" percent="67.9801" />
                                                                                        <WithSelf ticks="1025840" millisecs="102.5840" percent-cpu="0.0739" percent-wallclock="0.0739" />
                                                                                        <Method class="System.Runtime.CompilerServices.AsyncMethodBuilderCore+MoveNextRunner" name="Run" PID="21020">
                                                                                            <HitCount>1</HitCount>
                                                                                            <CPU ticks="942215406" millisecs="94221.5406" percent="67.9062" />
                                                                                            <Wallclock ticks="942215406" millisecs="94221.5406" percent="67.9062" />
                                                                                            <WithSelf ticks="0" millisecs="0.0000" percent-cpu="0.0000" percent-wallclock="0.0000" />
                                                                                            <Method class="System.Threading.ExecutionContext" name="Run" parameters="ExecutionContext executionContext, ContextCallback callback, object state, bool preserveSyncCtx" PID="21020">
                                                                                                <HitCount>1</HitCount>
                                                                                                <CPU ticks="942215406" millisecs="94221.5406" percent="67.9062" />
                                                                                                <Wallclock ticks="942215406" millisecs="94221.5406" percent="67.9062" />
                                                                                                <WithSelf ticks="1434582" millisecs="143.4582" percent-cpu="0.1034" percent-wallclock="0.1034" />
                                                                                                <Method class="System.Threading.ExecutionContext" name="RunInternal" parameters="ExecutionContext executionContext, ContextCallback callback, object state, bool preserveSyncCtx" PID="21020">
                                                                                                    <HitCount>1</HitCount>
                                                                                                    <CPU ticks="940780824" millisecs="94078.0824" percent="67.8028" />
                                                                                                    <Wallclock ticks="940780824" millisecs="94078.0824" percent="67.8028" />
                                                                                                    <WithSelf ticks="8052350" millisecs="805.2350" percent-cpu="0.5803" percent-wallclock="0.5803" />
                                                                                                    <Method class="WatsonTcp.WatsonMessage+&lt;BuildFromStream&gt;d__33" name="MoveNext" PID="21020" has-source="yes">
                                                                                                        <HitCount>1</HitCount>
                                                                                                        <CPU ticks="932728474" millisecs="93272.8474" percent="67.2225" />
                                                                                                        <Wallclock ticks="932728474" millisecs="93272.8474" percent="67.2225" />
                                                                                                        <WithSelf ticks="193464567" millisecs="19346.4567" percent-cpu="13.9431" percent-wallclock="13.9431" />
                                                                                                        <Method class="System.Linq.Enumerable" name="ToArray&lt;byte&gt;" parameters="IEnumerable&lt;TSource&gt; source" PID="21020">
                                                                                                            <HitCount>1</HitCount>
                                                                                                            <CPU ticks="732883778" millisecs="73288.3778" percent="52.8195" />
                                                                                                            <Wallclock ticks="732883778" millisecs="73288.3778" percent="52.8195" />
                                                                                                            <WithSelf ticks="2536834" millisecs="253.6834" percent-cpu="0.1828" percent-wallclock="0.1828" />
                                                                                                            <Method class="System.Linq.Buffer&lt;byte&gt;." name="ctor" parameters="IEnumerable&lt;TElement&gt; source" PID="21020">
                                                                                                                <HitCount>1</HitCount>
                                                                                                                <CPU ticks="730346944" millisecs="73034.6944" percent="52.6367" />
                                                                                                                <Wallclock ticks="730346944" millisecs="73034.6944" percent="52.6367" />
                                                                                                                <WithSelf ticks="1787277" millisecs="178.7277" percent-cpu="0.1288" percent-wallclock="0.1288" />
                                                                                                                <Method class="System.Linq.Enumerable+&lt;TakeIterator&gt;d__25&lt;byte&gt;" name="MoveNext" PID="21020">
                                                                                                                    <HitCount>1</HitCount>
                                                                                                                    <CPU ticks="728559667" millisecs="72855.9667" percent="52.5079" />
                                                                                                                    <Wallclock ticks="728559667" millisecs="72855.9667" percent="52.5079" />
                                                                                                                    <WithSelf ticks="703653509" millisecs="70365.3509" percent-cpu="50.7129" percent-wallclock="50.7129" />
                                                                                                                    <Method class="System.Linq.Enumerable+&lt;SkipIterator&gt;d__31&lt;byte&gt;" name="MoveNext" PID="21020">
                                                                                                                        <HitCount>1</HitCount>
                                                                                                                        <CPU ticks="24906158" millisecs="2490.6158" percent="1.7950" />
                                                                                                                        <Wallclock ticks="24906158" millisecs="2490.6158" percent="1.7950" />
                                                                                                                        <WithSelf ticks="24906158" millisecs="2490.6158" percent-cpu="1.7950" percent-wallclock="1.7950" />
                                                                                                                    </Method>
                                                                                                                </Method>
                                                                                                            </Method>
                                                                                                        </Method>
                                                                                                    </Method>
                                                                                                </Method>
                                                                                            </Method>
                                                                                        </Method>
                                                                                    </Method>
                                                                                </Method>
                                                                            </Method>
                                                                        </Method>
                                                                    </Method>
                                                                </Method>
                                                            </Method>
                                                        </Method>
                                                    </Method>
                                                </Method>
                                            </Method>
                                        </Method>
                                    </Method>
                                </Method>
                            </Method>
                        </Method>
                    </Method>
                </Method>
            </Method>
        </Method>
        <Method class="System.Threading.ThreadHelper" name="ThreadStart" PID="21020">
            <HitCount>1</HitCount>
            <CPU ticks="196884978" millisecs="19688.4978" percent="14.1897" />
            <Wallclock ticks="196884978" millisecs="19688.4978" percent="14.1897" />
            <WithSelf ticks="0" millisecs="0.0000" percent-cpu="0.0000" percent-wallclock="0.0000" />
            <Method class="System.Threading.ExecutionContext" name="Run" parameters="ExecutionContext executionContext, ContextCallback callback, object state" PID="21020">
                <HitCount>1</HitCount>
                <CPU ticks="196884978" millisecs="19688.4978" percent="14.1897" />
                <Wallclock ticks="196884978" millisecs="19688.4978" percent="14.1897" />
                <WithSelf ticks="0" millisecs="0.0000" percent-cpu="0.0000" percent-wallclock="0.0000" />
                <Method class="System.Threading.ExecutionContext" name="Run" parameters="ExecutionContext executionContext, ContextCallback callback, object state, bool preserveSyncCtx" PID="21020">
                    <HitCount>1</HitCount>
                    <CPU ticks="196884978" millisecs="19688.4978" percent="14.1897" />
                    <Wallclock ticks="196884978" millisecs="19688.4978" percent="14.1897" />
                    <WithSelf ticks="0" millisecs="0.0000" percent-cpu="0.0000" percent-wallclock="0.0000" />
                    <Method class="System.Threading.ExecutionContext" name="RunInternal" parameters="ExecutionContext executionContext, ContextCallback callback, object state, bool preserveSyncCtx" PID="21020">
                        <HitCount>1</HitCount>
                        <CPU ticks="196884978" millisecs="19688.4978" percent="14.1897" />
                        <Wallclock ticks="196884978" millisecs="19688.4978" percent="14.1897" />
                        <WithSelf ticks="0" millisecs="0.0000" percent-cpu="0.0000" percent-wallclock="0.0000" />
                        <Method class="PRServer.Logger" name="Flush" PID="21020" has-source="yes">
                            <HitCount>1</HitCount>
                            <CPU ticks="196884978" millisecs="19688.4978" percent="14.1897" />
                            <Wallclock ticks="196884978" millisecs="19688.4978" percent="14.1897" />
                            <WithSelf ticks="0" millisecs="0.0000" percent-cpu="0.0000" percent-wallclock="0.0000" />
                            <Method class="System.Threading.Thread" name="Sleep" parameters="int millisecondsTimeout" PID="21020">
                                <HitCount>1</HitCount>
                                <CPU ticks="196884978" millisecs="19688.4978" percent="14.1897" />
                                <Wallclock ticks="196884978" millisecs="19688.4978" percent="14.1897" />
                                <WithSelf ticks="196884978" millisecs="19688.4978" percent-cpu="14.1897" percent-wallclock="14.1897" />
                            </Method>
                        </Method>
                    </Method>
                </Method>
            </Method>
        </Method>
        <Method class="PRServer.Program" name="Main" PID="21020" has-source="yes">
            <HitCount>1</HitCount>
            <CPU ticks="196884620" millisecs="19688.4620" percent="14.1896" />
            <Wallclock ticks="196884620" millisecs="19688.4620" percent="14.1896" />
            <WithSelf ticks="0" millisecs="0.0000" percent-cpu="0.0000" percent-wallclock="0.0000" />
            <Method class="System.Windows.Forms.Application+ThreadContext" name="RunMessageLoop" parameters="int reason, ApplicationContext context" PID="21020">
                <HitCount>1</HitCount>
                <CPU ticks="196884620" millisecs="19688.4620" percent="14.1896" />
                <Wallclock ticks="196884620" millisecs="19688.4620" percent="14.1896" />
                <WithSelf ticks="0" millisecs="0.0000" percent-cpu="0.0000" percent-wallclock="0.0000" />
                <Method class="System.Windows.Forms.Application+ThreadContext" name="RunMessageLoopInner" parameters="int reason, ApplicationContext context" PID="21020">
                    <HitCount>1</HitCount>
                    <CPU ticks="196884620" millisecs="19688.4620" percent="14.1896" />
                    <Wallclock ticks="196884620" millisecs="19688.4620" percent="14.1896" />
                    <WithSelf ticks="0" millisecs="0.0000" percent-cpu="0.0000" percent-wallclock="0.0000" />
                    <Method class="System.Windows.Forms.Application+ComponentManager.System.Windows.Forms.UnsafeNativeMethods.IMsoComponentManager" name="FPushMessageLoop" parameters="IntPtr dwComponentID, int reason, int pvLoopData" PID="21020">
                        <HitCount>1</HitCount>
                        <CPU ticks="196884620" millisecs="19688.4620" percent="14.1896" />
                        <Wallclock ticks="196884620" millisecs="19688.4620" percent="14.1896" />
                        <WithSelf ticks="196758810" millisecs="19675.8810" percent-cpu="14.1806" percent-wallclock="14.1806" />
                    </Method>
                </Method>
            </Method>
        </Method>
    </CallTree>
</PerformanceData>
```

**Comment by Jyck** [comment] 2020-12-18 19:00
ok here is the error:
endCheck = 0,0,0,0
so i added a 0 Header check.
if so we return false, disconnect is fine now.

```
 internal async Task<bool> BuildFromStream(CancellationToken token)
        {
            // {"len":0,"s":"Normal"}\r\n\r\n
            byte[] headerBytes = new byte[24];

            try
            {
                #region Read-Headers

                await _DataStream.ReadAsync(headerBytes, 0, 24, token).ConfigureAwait(false); 
                byte[] headerBuffer = new byte[1];

                while (true)
                {
                    byte[] endCheck = headerBytes.Skip(headerBytes.Length - 4).Take(4).ToArray();
                    **if ((int)endCheck[3] == 0
                       && (int)endCheck[2] == 0
                       && (int)endCheck[1] == 0
                       && (int)endCheck[0] == 0)
                    {
                        _Logger?.Invoke(_Header + "0 Header");
                        return false;
                    }**

                    if ((int)endCheck[3] == 10
                        && (int)endCheck[2] == 13
                        && (int)endCheck[1] == 10
                        && (int)endCheck[0] == 13)
                    {
                        _Logger?.Invoke(_Header + "found header demarcation");
                        break;
                    }
....
```

logs: 18:58:43 [WatsonTcpServer] starting with SSL on 192.168.2.170:59141
18:58:45 [WatsonTcpServer] accepted connection from 192.168.2.170:59090
18:58:46 [WatsonTcpServer] requesting authentication material from 192.168.2.170:59090
18:58:46 [WatsonTcpServer] starting data receiver for 192.168.2.170:59090
18:58:46 [WatsonMessage] found header demarcation
18:58:46 [WatsonMessage] header processing complete
{"s":"AuthRequested","len":0,"psk":"xxxx"}
18:58:46 [WatsonTcpServer] message received from unauthenticated endpoint 192.168.2.170:59090
18:58:46 [WatsonTcpServer] accepted authentication for 192.168.2.170:59090
18:58:46 [WatsonMessage] found header demarcation
18:58:46 [WatsonMessage] header processing complete
{"s":"Normal","len":16,"md":{}}
18:58:46 [WatsonMessage] found header demarcation
18:58:46 [WatsonMessage] header processing complete
{"s":"Normal","len":12,"md":{"xxxxxx"}}
**18:58:50 [WatsonMessage] 0 Header**
18:58:50 [WatsonTcpServer] disconnect detected for client 192.168.2.170:59090
18:58:50 [WatsonTcpServer] client 192.168.2.170:59090 disconnected

**Comment by jchristn** [comment] 2020-12-18 19:27
Hi @Jyck here they are, thanks for finding this!  Hope you don't mind I added your name to the README.

NuGet: https://www.nuget.org/packages/WatsonTcp/4.7.0.1
Commit: https://github.com/jchristn/WatsonTcp/commit/fc745029507ee7ac6719644e6bf8e6e93b8b399d

Cheers, Joel

**Comment by BB2DTeam** [comment] 2023-06-08 08:46
I feel this problem still exists in version 5.1.2.
I often have to go to the Server to check the current CPU consumption, what I do is if the load is too high, then restart the Wastson Server.

**Comment by BB2DTeam** [comment] 2023-06-08 08:46
I feel this problem still exists in Version 5.1.2.
I often have to go to the Server to check the current CPU consumption, what I do is if the load is too high, then restart the Wastson Server.

**Comment by binbon2d** [comment] 2023-06-08 08:47
I feel this problem still exists in Version 5.1.2.
I often have to go to the Server to check the current CPU consumption, what I do is if the load is too high, then restart the Wastson Server.

**Comment by jchristn** [comment] 2023-06-08 14:17
Hi @binbon2d could you provide more tracing information or source code that reproduces the error?

**Comment by brianhama** [comment] 2023-08-08 18:24
I can confirm that I'm seeing this issue on Windows Server 2022.

**Comment by jchristn** [comment] 2023-08-08 18:39
Been a minute @brianhama :)  I'll re-open and investigate.  How have you been?

**Comment by brianhama** [comment] 2023-08-08 18:49
I was wondering if that was you. Small world lol

**Comment by brianhama** [comment] 2023-08-10 03:36
@jchristn, I had been seeing the issue while using the project's nuget package. I just cloned the project's latest code so that I could help debug the problem and, so far, I have been unable to reproduce the issue, despite it being easily reproducible with the version in the nuget package. So I'm cautiously optimistic that the issue had already been resolved in the latest code and this issue can be closed. Thanks!

**Comment by jchristn** [comment] 2023-08-10 03:38
Thank you sir, I didn't have an opportunity to get to it today, but will tomorrow.  Glad to hear that when built from source the issue wasn't present.  If you have reproduction steps I could try that would be huge.  Thanks for your time!

**Comment by jchristn** [comment] 2023-08-10 16:59
I spent some time trying to reproduce this (granted, I don't have Windows Server 2022 readily available, just Windows 10 and 11) and could not, through a combination of process aborts, disconnects, cancellations, and disposal.

**Comment by jchristn** [comment] 2023-08-13 16:34
Sorry for the delay everyone, I just tested on Windows Server 2022 this morning and am unable to reproduce.  Are there specific steps I can follow?  As a precautionary measure I'll publish a new version on NuGet, in case somehow this fix isn't already there.

**Comment by jchristn** [comment] 2023-08-13 16:39
NuGet: https://www.nuget.org/packages/WatsonTcp/5.1.6
Commit: https://github.com/jchristn/WatsonTcp/commit/ec984fabd89516175398a51a1d9c66ba4df6dae4

Please let me know if you can reproduce using the latest!  

Also, on another note, there are a couple new ```Guid``` properties introduced - I have it in my backlog to allow the developer to specify the ```Guid``` values used for each (not implemented in this version)

**Comment by jchristn** [comment] 2023-08-19 22:04
Please re-open if the issue can be reproduced and steps can be provided.  Cheers

**Closed by jchristn** 2023-08-19 22:04 UTC
