### ISSUE TITLE
Compression issues (was GZip compression doesn't seem to work with SendAndWait)

### ISSUE THREAD

**Issue by Dijkstra-ru** [jchristn/WatsonTcp#85] opened 2020-07-02 09:12 UTC
Hello!

The control flow doesn't seem to enter the SyncRequestReceived event if GZip compression is enabled. Disabling compression fixes the issue.

Regards, Yury.

**Comment by jchristn** [comment] 2020-07-02 15:52
Hi @Dijkstra-ru thank you so much, I will check it out!

**Comment by Dijkstra-ru** [comment] 2020-07-02 15:56
> Hi @Dijkstra-ru thank you so much, I will check it out! What version are you using?

I use the lastest version from NuGet, namely 4.1.12.4.
I'm sorry I can't write a minimal code to reproduce the issue now, deadline is coming too soon. I think it will work with the most basic example from readme.

**Comment by jchristn** [comment] 2020-07-02 15:57
I was able to reproduce.

Client sending compressed message
```
Server IP: [127.0.0.1]
Server port: [9000]
Use SSL: [y/N]?
[WatsonTcpClient] Connecting to 127.0.0.1:9000
[WatsonTcpClient] Connected to server, starting data receiver
Server connected
Command [? for help]: comp
Compression [None|Deflate|Gzip]: [None] Deflate
Command [? for help]: send
Data: asdf
```

Server receives compressed message:
```
[WatsonMessage] ReadHeaders found header demarcation
[WatsonMessage] BuildFromStream header processing complete
{"Status":"Normal","SyncRequest":false,"SyncResponse":false,"Compression":"Deflate","ContentLength":4,"Metadata":{}}
Message received from 127.0.0.1:51773: asdf
```

Client sends/waits compressed message:
```
Command [? for help]: sendandwait
Data: hello
Timeout (milliseconds): [5000] 10000
[WatsonMessage] ReadHeaders found header demarcation
[WatsonMessage] BuildFromStream header processing complete
{"Status":"Normal","SyncRequest":false,"SyncResponse":true,"Expiration":"2020-07-02T08:55:54.9857246-07:00","ConversationGuid":"3ff7744d-c4cc-4796-b05e-f7ea64d7995f","Compression":"None","ContentLength":22,"Metadata":{"foo":"bar","bar":"baz"}}
Metadata:
  foo: bar
  bar: baz
Response: Here is your response!
Command [? for help]:
```

Server receives UNCOMPRESSED message:
```
[WatsonMessage] ReadHeaders found header demarcation
[WatsonMessage] BuildFromStream header processing complete
{"Status":"Normal","SyncRequest":true,"SyncResponse":false,"SenderTimestamp":"2020-07-02T08:55:44.9857246-07:00","Expiration":"2020-07-02T08:55:54.9857246-07:00","ConversationGuid":"3ff7744d-c4cc-4796-b05e-f7ea64d7995f","Compression":"Deflate","ContentLength":5,"Metadata":{}}
Synchronous request received from 127.0.0.1:51773: hello
Sending synchronous response
```

**Comment by jchristn** [comment] 2020-07-02 15:59
Actually, this may or may not be cosmetic.  It looks like the client is NOT setting the compression enum, but somehow the server is picking it up.

Nevertheless, I'll dig into this.  Sorry for the inconvenience!

**Comment by jchristn** [comment] 2020-07-02 16:11
My mistake; the server did not have its default compression set in my previous test, which is why the server response included ```"Compression":"None"``` though the client message was sent with ```"Compression":"Deflate"```.

The client seems to be operating properly:
1) Client sending uncompressed message, server receives:
```
{"Status":"Normal","SyncRequest":false,"SyncResponse":false,"Compression":"None","ContentLength":14,"Metadata":{}}
Message received from 127.0.0.1:51852: no compression
```
2) Client sending deflate message, server receives:
```
{"Status":"Normal","SyncRequest":false,"SyncResponse":false,"Compression":"Deflate","ContentLength":19,"Metadata":{}}
Message received from 127.0.0.1:51852: deflate compression
```
3) Client sending gzip message, server receives:
```
{"Status":"Normal","SyncRequest":false,"SyncResponse":false,"Compression":"Gzip","ContentLength":16,"Metadata":{}}
Message received from 127.0.0.1:51852: gzip compression
```
4) Client sendandwait no compression, server receives:
```
{"Status":"Normal","SyncRequest":true,"SyncResponse":false,"SenderTimestamp":"2020-07-02T09:05:23.1512931-07:00","Expiration":"2020-07-02T09:05:28.1512931-07:00","ConversationGuid":"5f6bc1fe-a2dc-47ee-a104-093ffb38649a","Compression":"None","ContentLength":28,"Metadata":{}}
Synchronous request received from 127.0.0.1:51852: no compression send and wait
```
5) Client sendandwait deflate compression, server receives:
```
{"Status":"Normal","SyncRequest":true,"SyncResponse":false,"SenderTimestamp":"2020-07-02T09:06:24.75965-07:00","Expiration":"2020-07-02T09:06:29.75965-07:00","ConversationGuid":"09ed98aa-4f12-47cc-91eb-12e584ed61b8","Compression":"Deflate","ContentLength":19,"Metadata":{}}
Synchronous request received from 127.0.0.1:51852: deflate compression
```
6) Client sendandwait gzip compression, server receives:
```
{"Status":"Normal","SyncRequest":true,"SyncResponse":false,"SenderTimestamp":"2020-07-02T09:06:49.9916456-07:00","Expiration":"2020-07-02T09:06:54.9916456-07:00","ConversationGuid":"c33516d6-dc37-4459-948f-a6fe25274e2b","Compression":"Gzip","ContentLength":16,"Metadata":{}}
Synchronous request received from 127.0.0.1:51852: gzip compression
```

In terms of the server initiating...
1) Server send no compression, client receives:
```
{"Status":"Normal","SyncRequest":false,"SyncResponse":false,"Compression":"None","ContentLength":14,"Metadata":{}}
Message from server: no compression
```
2) Server send with deflate compression, client receives:
```
{"Status":"Normal","SyncRequest":false,"SyncResponse":false,"Compression":"Deflate","ContentLength":19,"Metadata":{}}
Message from server: deflate compression
```
3) Server send with gzip compression, client receives:
```
{"Status":"Normal","SyncRequest":false,"SyncResponse":false,"Compression":"Deflate","ContentLength":19,"Metadata":{}}
Message from server: deflate compression
```
4) Server sendandwait no compression, client receives:
```
{"Status":"Normal","SyncRequest":true,"SyncResponse":false,"SenderTimestamp":"2020-07-02T09:08:54.5461946-07:00","Expiration":"2020-07-02T09:08:59.5461946-07:00","ConversationGuid":"4803d2fa-594f-4dfe-b9d2-9c73a324cb8b","Compression":"None","ContentLength":14,"Metadata":{}}
Message received from 127.0.0.1:9000: no compression
```
5) Server sendandwait deflate compression, client receives:
```
{"Status":"Normal","SyncRequest":true,"SyncResponse":false,"SenderTimestamp":"2020-07-02T09:09:23.3351217-07:00","Expiration":"2020-07-02T09:09:28.3351217-07:00","ConversationGuid":"f3db3def-330c-4580-acd0-4d3562b7279d","Compression":"Deflate","ContentLength":19,"Metadata":{}}
Message received from 127.0.0.1:9000: deflate compression
```
6) Server sendandwait gzip compression, client receives:
```
{"Status":"Normal","SyncRequest":true,"SyncResponse":false,"SenderTimestamp":"2020-07-02T09:09:50.0789243-07:00","Expiration":"2020-07-02T09:09:55.0789243-07:00","ConversationGuid":"ac72c03b-4e9c-4838-b627-131b0c516974","Compression":"Gzip","ContentLength":16,"Metadata":{}}
Message received from 127.0.0.1:9000: gzip compression
```

Please ignore my previous comment.  It appears the messages are indeed going out with the specified compression applied.  

Is the concern that the client/server sends with one form of compression and gets a response from sendandwait using a different form?  If so, that is by design - the client/server will send with whatever compression is defined on the client/server, not based on any incoming message.

If that's not the concern, I'd love it if you could produce a small code snippet to reproduce.  It appears to be ok on my end but I'm more than happy to investigate further!

Cheers, Joel

**Comment by Dijkstra-ru** [comment] 2020-07-02 16:55
Strangely, I can't reproduce it in a simple sample code, however commenting `client.Compression = CompressionType.Gzip;` fixes the situation in real-world code. I need some time to think it over.

My code is identical to this, but it doesn't work with `client.Compression = CompressionType.Gzip;` uncommented. The code below works either way.
```
using System;
using WatsonTcp;
static class Program {
  static void Main() {
    var server = new WatsonTcpServer("127.0.0.1", 12345);
    var client = new WatsonTcpClient("127.0.0.1", 12345);
    client.Compression = CompressionType.Gzip;
    server.MessageReceived += (sender, args) => { };
    server.SyncRequestReceived += OnServerSyncRequestReceived;
    server.Start();
    client.MessageReceived += (sender, args) => { };
    client.Start();
    var resp = client.SendAndWait(5000, new byte[] {1});
    Console.ReadLine();
  }
  static SyncResponse OnServerSyncRequestReceived(SyncRequest request) {
    Console.WriteLine("Entered server code");
    return new SyncResponse(request, new byte[] {1});
  }
}
```
Please leave the issue open for a few days, I'll try to make the minimal reproducing sample.

P.S. I also want to thank you for your work. You saved our team lots of time and nerves. We're using WatsonTCP for a few years, modified (to exclude framing, like in your other project) and not modified in a traffic light controller dispatch program in Russia. Your code manages hundreds of traffic lights simultaneously without any problems.

**Comment by jchristn** [comment] 2020-07-02 17:20
Thank you for the kind words!  I am happy to support in whatever way I can. Please don’t hesitate to ask :) Cheers Joel

**Comment by jchristn** [comment] 2020-07-19 19:49
Hi @Dijkstra-ru were you able to track down the source of the problem?  Cheers, Joel

**Comment by jchristn** [comment] 2020-07-25 01:42
Hi @Dijkstra-ru please feel free to reopen if you find the issue is in the library.  Cheers!

**Comment by developervariety** [comment] 2020-07-27 01:42
I was able to produce this bug.

## POC
* Set `Compression` to `CompressionType.Gzip` on client and server
* Send a `SendAndWait` packet with a `Dictionary (metadata)`, any timeout and a string/byte array

`WatsonTcpServer` never "receives" the packet.

**Comment by developervariety** [comment] 2020-07-27 01:46
Logger logs from `WatsonTcpServer`. It appears it parses the message, but never invokes the event handler when using `CompressionType.Gzip`

```json
{"Timestamp":"2020-07-26T21:44:51.8197627-04:00","Level":"Verbose","MessageTemplate":"[Tcp] [WatsonTcpServer] Starting on 0.0.0.0:8080"}
{"Timestamp":"2020-07-26T21:44:57.8427123-04:00","Level":"Verbose","MessageTemplate":"[Tcp] [WatsonTcpServer] Accepted connection from 127.0.0.1:53215"}
{"Timestamp":"2020-07-26T21:44:57.8469483-04:00","Level":"Verbose","MessageTemplate":"[Tcp] [WatsonTcpServer] Starting data receiver for 127.0.0.1:53215"}
{"Timestamp":"2020-07-26T21:44:57.8478152-04:00","Level":"Information","MessageTemplate":"[Network] Client connected. [IP Address: 127.0.0.1:53215]"}
{"Timestamp":"2020-07-26T21:45:02.6801905-04:00","Level":"Verbose","MessageTemplate":"[Tcp] [WatsonMessage] ReadHeaders found header demarcation"}
{"Timestamp":"2020-07-26T21:45:03.0443340-04:00","Level":"Verbose","MessageTemplate":"[Tcp] [WatsonMessage] BuildFromStream header processing complete\r\n{\"Status\":\"Normal\",\"SyncRequest\":true,\"SyncResponse\":false,\"SenderTimestamp\":\"2020-07-26T21:45:02.3564525-04:00\",\"Expiration\":\"2020-07-26T22:01:42.3554372-04:00\",\"ConversationGuid\":\"9903f03f-c63b-4de1-9f33-f21cec9c8d62\",\"Compression\":\"Gzip\",\"ContentLength\":75579,\"Metadata\":{\"gameType\":1,\"baseAngle\":60.0}}"}
```

**Comment by jchristn** [comment] 2020-07-27 02:19
Hi @Dijkstra-ru and @developervariety I modified ```Test.Client``` to automatically add a ```Dictionary<object, object>``` to the metadata parameter, set the client compression to Gzip, and sent a message to the server.  As you can see in the screenshot below the server receives the message.

Would love some help in reproducing this.

![image](https://user-images.githubusercontent.com/1421081/88497215-8b648c80-cf74-11ea-80ec-08322d1e2c6d.png)

![image](https://user-images.githubusercontent.com/1421081/88497239-9b7c6c00-cf74-11ea-95f7-161fd5d0cb26.png)

The client code:
```
        private static void SendAndWait()
        {
            string userInput = InputString("Data:", null, false);
            int timeoutMs = InputInteger("Timeout (milliseconds):", 5000, true, false);
            Dictionary<object, object> metadata = new Dictionary<object, object>();
            metadata.Add("foo", "bar");

            try
            {
                SyncResponse resp = client.SendAndWait(metadata, timeoutMs, userInput);
                if (resp.Metadata != null && resp.Metadata.Count > 0)
                {
                    Console.WriteLine("Metadata:");
                    foreach (KeyValuePair<object, object> curr in resp.Metadata)
                    {
                        Console.WriteLine("  " + curr.Key.ToString() + ": " + curr.Value.ToString());
                    }
                }

                Console.WriteLine("Response: " + Encoding.UTF8.GetString(resp.Data));
            }
            catch (Exception e)
            {
                Console.WriteLine("Exception: " + e.ToString());
            }
        }
```

You can see I set the client compression here:
![image](https://user-images.githubusercontent.com/1421081/88497270-b9e26780-cf74-11ea-9dca-2a53eafb7331.png)

And the server received the compressed message and processed the payload:
![image](https://user-images.githubusercontent.com/1421081/88497299-cbc40a80-cf74-11ea-8335-19bb07684261.png)

I'm definitely not ruling out that there is something in the library; I just can't reproduce it.  If you could share a gist with a code sample that produces this bug, please let me know!  

Re-opening for you now.

Thanks, Joel

**Comment by developervariety** [comment] 2020-07-28 16:12
I'm not entirely sure how I was able to reproduce this, but I know it wasn't a false positive. Next time it occurs I'll have you a detailed POC.

**Comment by jchristn** [comment] 2020-07-28 16:24
Are you setting the SyncMessageReceived callback?  I'm assuming you are but thought it would be worthwhile to double check.

**Comment by Job79** [comment] 2020-07-29 12:30
Hello, just adding that Gzip doesn't work for my at all (linux, .net core 3.1.6)
Here is my code:
```cs
        [Test]
        public async Task TestCompression()
        {
            var watsonServer = new WatsonTcpServer("127.0.0.1", _watsonTcpPort)
            {
                Compression = CompressionType.Gzip,
                Logger = Console.WriteLine
            };
            
            watsonServer.MessageReceived += (sender, message) =>
            {
                Console.WriteLine(Encoding.UTF8.GetString(message.Data));
                watsonServer.Send(message.IpPort, message.Data);
            };
            watsonServer.Start();
            await Task.Delay(100);
            
            var client = new WatsonTcpClient("127.0.0.1", _watsonTcpPort)
            {
                Compression = CompressionType.Gzip,
                Logger = Console.WriteLine
            };

            int counter = 0;
            client.MessageReceived += (sender, message) =>
            {
                Console.WriteLine(Encoding.UTF8.GetString(message.Data));
                Interlocked.Increment(ref counter);
            };
            client.Start();

            await client.SendAsync("Hello");

            TestHelper.WaitWhileFalse(() => counter == 1);
            Assert.AreEqual(1, counter);
        }
```

And the output:
```
[WatsonTcpServer] Starting on 127.0.0.1:1201
[WatsonTcpClient] Connecting to 127.0.0.1:1201
[WatsonTcpClient] Connected to server, starting data receiver
[WatsonTcpServer] Accepted connection from 127.0.0.1:42872
[WatsonTcpServer] Starting data receiver for 127.0.0.1:42872
```

The server doesn't receive any data. Maybe related to #84 ?
Code works fine with `CompressionType.Deflate` and `CompressionType.None`

**Comment by jchristn** [comment] 2020-07-29 15:29
Got it, was able to reproduce.  Thanks @Job79 - I will test and remedy!

![image](https://user-images.githubusercontent.com/1421081/88819976-93d7e580-d175-11ea-9173-35a32adc84a7.png)

**Comment by jchristn** [comment] 2020-07-29 15:58
Ok I think I've solved it.  I was having an issue early on where if I were to read some n bytes out of the ```GZipStream``` there would be remnants leftover in the underlying ```NetworkStream```, so I had to switch to reading the ```GZipStream``` fully.  

Now, somehow, reading n bytes works.

I'm going to test this with Deflate as well and make sure there are no issues.  Then I will test on Ubuntu with .NET Core 3.1. 

More to come.

**Comment by jchristn** [comment] 2020-07-29 16:33
There is clearly a difference in how Windows and Ubuntu handle GZipStream and DeflateStream.  And it's really frustrating. 

I updated NuGet to v4.1.2.15 with a fix.  Here are the results:

- Windows with Gzip: pass
- Windows with Deflate: pass
- Ubuntu with Gzip: pass (fixed)
- Ubuntu with Deflate: fail

The difference is this.  Earlier on I found that in order to properly process messages, anytime gzip or deflate were enabled I would have to fully read the stream rather than read some n number of bytes based on the message content length.  Otherwise, compression remnants would be left in the underlying network stream which would cause a deserialization exception when the next message was received.

It seems that the proper approach is to revert deflate back to fully reading the stream and test again so that I can get all four tests to pass.

More to come.

Ubuntu using Gzip:
![image](https://user-images.githubusercontent.com/1421081/88826927-2aa8a000-d17e-11ea-82d6-5fa4c65e0b52.png)

Ubuntu using Deflate:
![image](https://user-images.githubusercontent.com/1421081/88826317-71e26100-d17d-11ea-8a68-dc38c955822c.png)

Windows using Gzip:
![image](https://user-images.githubusercontent.com/1421081/88826353-7c9cf600-d17d-11ea-90fd-4ff6f7e88d29.png)

Windows using Deflate:
![image](https://user-images.githubusercontent.com/1421081/88826785-0220a600-d17e-11ea-9e7e-1acfb8bebd57.png)

**Comment by jchristn** [comment] 2020-07-29 16:44
## Test results using 4.1.12.6

This one uses selective read for Gzip and full read for Deflate.

Windows Gzip (pass):
![image](https://user-images.githubusercontent.com/1421081/88827805-4496b280-d17f-11ea-99f2-c37b402eb442.png)

Windows Deflate (pass):
![image](https://user-images.githubusercontent.com/1421081/88827871-57a98280-d17f-11ea-94e1-f0637c2b4a84.png)

Ubuntu Gzip (pass):
![image](https://user-images.githubusercontent.com/1421081/88828309-ed451200-d17f-11ea-8639-17c81319be0f.png)

Ubuntu Deflate (pass):
![image](https://user-images.githubusercontent.com/1421081/88828397-09e14a00-d180-11ea-8a52-cfe0459839a6.png)

**Comment by jchristn** [comment] 2020-07-29 16:44
So it looks like 4.1.12.6 fixes the issue.  Could you give it a go and see if it works for you?

**Comment by developervariety** [comment] 2020-07-29 16:46
Deflate was working with you reading the `NetworkStream`. I'll be updating my library and checking this out!

Thank you for your time and dedication.

**Comment by Job79** [comment] 2020-07-29 17:02
4.1.12.6 fixed the issue! Good work!

**Comment by jchristn** [comment] 2020-07-29 17:38
Glad to know, thanks for helping me isolate it!

**Comment by jchristn** [comment] 2020-08-11 03:00
Hi all, issues with Deflate and Gzip have crept up again and I'm about ready to pull them out of the code.  I wanted to get your feedback on it.  It seems various combinations of operating systems (Windows, Mac, Linux) vs runtimes (.NET Framework, .NET Framework with Mono, and .NET Core) have different behaviors with regard to fragments of data being left in the underlying stream.  

In any case, the GZipStream and DeflateStream straddle the underlying NetworkStream (or SslStream), and in some combination of the above it is expected that the compression stream must be read until the end of stream and in others only the specific number of bytes needed should be read.  

It seems wildly inconsistent that in one of the above combinations, if I write 10 bytes to a DeflateStream, I can't simply read 10 bytes from the DeflateStream on the other side (after wrapping the underlying stream with the DeflateStream); I have to read until the end of the stream.  Same with GZipStream.

With that said, I wanted to solicit your feedback on how much agony it would cause you if I did this.  I could provide static helper methods that could compress a stream or byte[] going into one of the Send methods, and could be called inside of your MessageReceived or StreamReceived methods.  But having that complexity inside of the library is becoming untenable.

Let me know your thoughts.  Thanks!  Joel

**Comment by Job79** [comment] 2020-08-11 06:52
> Hi all, issues with Deflate and Gzip have crept up again and I'm about ready to pull them out of the code.

The issues or the compression?

Maybe take a complete other approach, like building compression on top of the receive functions instead of embedding them.
This is how I would add compression:

- Give all the send functions an optional (Default: Compression.None) parameter with the compression type. When not none first compress the data before continuing.
- Give the message received parameter class a decompress function, this  decompresses the message when compressed (check here, Gzip has a magic number). Bonus points for letting this function return 'this'.

**Comment by jchristn** [comment] 2020-08-11 15:02
The compression.

There isn't a least common denominator implementation that works in all combinations of OS and runtime environment.

**Comment by jchristn** [comment] 2020-08-11 21:03
Hi all, I committed v4.2.0 just now (https://github.com/jchristn/WatsonTcp/commit/89dd514ce50cbca39051413ec7f0d8aec3b8405b) and published to NuGet (https://www.nuget.org/packages/WatsonTcp/4.2.0).  

There are a couple key changes:

1) You shouldn't be able to 'over-read' now when using streams, i.e. reading too many bytes and getting into the next message's header; this is applicable to when integrating using ```StreamReceived``` instead of ```MessageReceived```, and
2) Compression is gone, for now; it was causing too many problems across multiple OS and runtimes

I plan to re-add compression back in soon, but using an over-the-top model instead of something that encapsulates the underlying data stream.  

Cheers, Joel

**Closed by jchristn** 2020-08-11 21:03 UTC
