### ISSUE TITLE
How GUIDs work?

### ISSUE THREAD

**Issue by SnowdenDev** [jchristn/WatsonTcp#267] opened 2023-08-19 07:19 UTC
I am using WatsonTcp for my game anti-cheat program, I have a problem when trying to communicate with a specific user, I am using SendAsync(Ip:port,"sample"); but I get System.NullReferenceException: 'Object reference not set to an instance of an object.'
I can not understand how is the use of GUID? Can someone please give me a minute of your time to explain?

**Comment by jchristn** [comment] 2023-08-19 13:22
Hi @SnowdenDev could you provide the full exception/stack trace when using ```SendAsync``` with the ```string ipPort``` parameter?

The ```SendAsync(Guid guid...``` variants are the replacement for the ```ipPort``` variants.  ```ipPort``` was used as an internal identifier for a discrete TCP connection.  The primary motivators for moving away from this stem from the string comparison required to match a server-side send operation to a client connection.  

There should be, operationally, no difference between the two.  ```ConnectionEventArgs.Client``` includes both a ```Guid``` property and an ```IpPort``` property.

But in any case, the ```ipPort``` variant should work.  Please provide the full exception and stack trace along with sample code to reproduce and I'll look into it.  

Cheers, Joel

**Comment by SnowdenDev** [comment] 2023-08-20 22:55
Hi Joel, I've been taking a better look at my code, and I'm afraid I haven't explained my problem correctly, I don't think the error is your beautiful work (WatsonTcp), it turns out that if I can send a message referencing the endpoint as ip:port and it's wonderful ....
Having said this, I will tell you that I am suffering so much because I am new to this: my app is on winform, I have 2 forms, 1 the Main form where WatsonTcpServer is instantiated and another form where I want to use .Send(), invoke this function is the one that generates:
 System.NullReferenceException
  HResult=0x80004003
  Message = Object reference not set to an instance of an object.
  Origin = Server
so what would be a correct way to access .Send() from another form?
Please Great master

**Comment by jchristn** [comment] 2023-08-21 00:00
Hi @SnowdenDev using Windows Forms are always tricky.  Generally a forms app spawns from a ```static class Program```.  Perhaps you could add an ```internal static WatsonTcpServer Server``` within ```static class Program``` and then reference from within your form as ```Program.Server.Send...```.  Would this work for you?

**Comment by SnowdenDev** [comment] 2023-08-21 03:28
Hi Johel, I made it! Turns out I had to change the code that called the second form, use this: 

ScreenshotForm form2 = new ScreenshotForm();
            form2.MainForm = this;
            form2.ShowDialog(this);
            
And in the second form, instantiate the first:
 public ServerForm MainForm { get; set; } 
 
 Then to send the message:
 MainForm.Server.SendAsync(User.Ip, "Screenshot");
 
And that's how it worked perfectly, I take the events into account, an if condition is created at the beginning, which only proceeds if the bool type variable is true, that means that the event is enabled......
I would like to learn more about the GUID property? This would help me to know which specific user the message would be addressed to, but he needed to use it outside of events so he could not take it from there, you are great for what you have created, I saw your github profile and I admire you for everything .....

**Comment by jchristn** [comment] 2023-08-21 04:01
Thanks for the kind words @SnowdenDev - I'm glad that the library is useful to you!  

The ```ClientMetadata``` object contained within the ```ConnectionEventArgs``` object has a few properties that could be useful.

1) The ```Guid``` is a globally-unique identifier, and mathematically you can be confident that no matter how many concurrent clients you have, they will each have a unique value.  You can think of this as a random/unique session identifier.  The main reason you'd want to use this vs the ```IpPort``` is because, internally, parsing strings and doing string comparisons is far more costly that doing comparisons on GUIDs.  

2) The ```IpPort``` is taken directly from the socket, specifically the ```RemoteEndPoint```.  Earlier versions used this as a means of identifying each client and it was the property that you passed into the ```Send``` method to specify to whom you'd like the send the message.

3) The ```Name``` property is something you set.  You can use whatever you want.  But, you can't use it as a means of identifying a client when performing a ```Send```

4) The ```Metadata``` property is an object that you can attach to the client metadata.  You can attach whatever you want.  This is helpful if you want to attach state to the client metadata record directly.

I'll go ahead and close this since it sounds like you have everything sorted.  Thanks again for the kind words (it means a lot!) and please let me know if anything else comes up.  Cheers, Joel

**Closed by jchristn** 2023-08-21 04:01 UTC
